name: React build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSH-deploy
        uses: appleboy/ssh-action@master 
        with: 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }} 
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/app/front/SEcodeverse-Front
            git pull
            cd /home/ubuntu/app/front
            chmod +x deploy.sh
            ./deploy.sh
